### ISSUE TITLE
Labels syncer and pull request labeler  

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1526]
🐞 **Problem**
Managing GitHub labels manually can become a mess. However, it is possible to define those within a file called `.github/labels.yml` and sync those via GitHub workflows. Labels are defined using the following scheme:

```yml
- name: bug
  description: Something isn't working
  color: d42a34

- name: dependencies
  description: Related with project dependencies
  color: ffc0cb

- name: documentation
  description: Improvements or additions to documentation
  color: 0677ba

- name: enhancement
  description: New features or code improvements
  color: FFD827

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50
```

On top of that, it is possible to enable an automatic pull request labeler which applies a label depending the files which have been modified. For implementing this labeler, the following files are required: `.github/labeler.yml` and `.github/workflows/label.yml`.

The first one defines the label to be applied regarding modified files. The later is the workflow which will apply the label within the PR. If new files get modified within a PR, the labeler will update those.
